const CONFIG={SPREADSHEET_ID:'PASTE_SPREADSHEET_ID_HERE',SELLER_SHEET:'SELLER_MASTER',DATA_SHEET:'RETUR_DATA',TIMEZONE:'Asia/Jakarta'};
function setupSheets(){const ss=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);let s=ss.getSheetByName(CONFIG.SELLER_SHEET);if(!s)s=ss.insertSheet(CONFIG.SELLER_SHEET);if(s.getLastRow()===0)s.appendRow(['seller_id','seller_name','active','created_at']);let d=ss.getSheetByName(CONFIG.DATA_SHEET);if(!d)d=ss.insertSheet(CONFIG.DATA_SHEET);if(d.getLastRow()===0)d.appendRow(['timestamp','awb','seller_name','source']);}
function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function doGet(){return out_({ok:true,service:'retur-bgg16',time:new Date().toISOString()});}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}');if(b.action==='getSellers')return out_({ok:true,data:getSellers_()});if(b.action==='addSeller')return out_({ok:true,data:addSeller_(b.name)});if(b.action==='saveReturns')return out_({ok:true,data:saveReturns_(b)});if(b.action==='searchReturns')return out_({ok:true,data:searchReturns_(b)});throw Error('Action tidak dikenali.');}catch(err){return out_({ok:false,message:err.message||String(err)});}}
function getSellers_(){setupSheets();const v=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID).getSheetByName(CONFIG.SELLER_SHEET).getDataRange().getValues();if(v.length<=1)return[];return v.slice(1).filter(r=>String(r[1]).trim()&&String(r[2]).toLowerCase()!=='false').map(r=>({id:String(r[0]),name:String(r[1]).trim()}));}
function addSeller_(name){setupSheets();name=String(name||'').trim();if(!name)throw Error('Nama seller wajib diisi.');const ss=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID),sh=ss.getSheetByName(CONFIG.SELLER_SHEET),hit=getSellers_().find(s=>s.name.toLowerCase()===name.toLowerCase());if(hit)return hit;const item={id:Utilities.getUuid(),name};sh.appendRow([item.id,item.name,true,new Date()]);return item;}
function norm_(x){return String(x||'').trim().replace(/\s+/g,'').toUpperCase();}
function existing_(sh){const v=sh.getDataRange().getValues(),set=new Set();for(let i=1;i<v.length;i++)set.add(norm_(v[i][1]));return set;}
function saveReturns_(b){setupSheets();const seller=String(b.sellerName||'').trim();if(!seller)throw Error('Seller wajib diisi.');const awbs=[...new Set((Array.isArray(b.awbs)?b.awbs:[]).map(norm_).filter(Boolean))];if(!awbs.length)throw Error('Minimal satu AWB diperlukan.');const sh=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID).getSheetByName(CONFIG.DATA_SHEET),set=existing_(sh),fresh=awbs.filter(a=>!set.has(a));if(!fresh.length)throw Error('Semua AWB sudah pernah dicatat.');const now=new Date();sh.getRange(sh.getLastRow()+1,1,fresh.length,4).setValues(fresh.map(a=>[now,a,seller,'WEB']));return{savedCount:fresh.length,skippedCount:awbs.length-fresh.length,timestampText:Utilities.formatDate(now,CONFIG.TIMEZONE,'dd/MM/yyyy HH:mm:ss')};}
function searchReturns_(b){setupSheets();const q=norm_(b.q||''),seller=String(b.sellerName||'').trim().toLowerCase();if(q.length<3)return[];const v=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID).getSheetByName(CONFIG.DATA_SHEET).getDataRange().getValues(),out=[];for(let i=1;i<v.length;i++){const ts=v[i][0],awb=norm_(v[i][1]),sn=String(v[i][2]||'');if(awb.indexOf(q)===-1)continue;if(seller&&sn.toLowerCase()!==seller)continue;out.push({timestampText:ts?Utilities.formatDate(new Date(ts),CONFIG.TIMEZONE,'dd/MM/yyyy HH:mm:ss'):'',awb,sellerName:sn});}return out.reverse().slice(0,200);}
